namespace ResearchDataset.Utils
{
    public class ArXivCategoryTaxonomy
    {
        public class ArXivCategory
        {
            public string? Code { get; set; }
            public string? Description { get; set; }
        }

        public static List<ArXivCategory> CategoriesList
        {
            get
            {
                return new List<ArXivCategory>
                {
                    new ArXivCategory {Code = "cs.AI", Description = "Artificial Intelligence"},
                    new ArXivCategory {Code = "cs.AR", Description = "Hardware Architecture"},
                    new ArXivCategory {Code = "cs.CC", Description = "Computational Complexity"},
                    new ArXivCategory {Code = "cs.CE", Description = "Computational Engineering, Finance, and Science"},
                    new ArXivCategory {Code = "cs.CG", Description = "Computational Geometry"},
                    new ArXivCategory {Code = "cs.CL", Description = "Computation and Language"},
                    new ArXivCategory {Code = "cs.CR", Description = "Cryptography and Security"},
                    new ArXivCategory {Code = "cs.CV", Description = "Computer Vision and Pattern Recognition"},
                    new ArXivCategory {Code = "cs.CY", Description = "Computers and Society"},
                    new ArXivCategory {Code = "cs.DB", Description = "Databases"},
                    new ArXivCategory {Code = "cs.DC", Description = "Distributed, Parallel, and Cluster Computing"},
                    new ArXivCategory {Code = "cs.DL", Description = "Digital Libraries"},
                    new ArXivCategory {Code = "cs.DM", Description = "Discrete Mathematics"},
                    new ArXivCategory {Code = "cs.DS", Description = "Data Structures and Algorithms"},
                    new ArXivCategory {Code = "cs.ET", Description = "Emerging Technologies"},
                    new ArXivCategory {Code = "cs.FL", Description = "Formal Languages and Automata Theory"},
                    new ArXivCategory {Code = "cs.GL", Description = "General Literature"},
                    new ArXivCategory {Code = "cs.GR", Description = "Graphics"},
                    new ArXivCategory {Code = "cs.GT", Description = "Computer Science and Game Theory"},
                    new ArXivCategory {Code = "cs.HC", Description = "Human-Computer Interaction"},
                    new ArXivCategory {Code = "cs.IR", Description = "Information Retrieval"},
                    new ArXivCategory {Code = "cs.IT", Description = "Information Theory"},
                    new ArXivCategory {Code = "cs.LG", Description = "Machine Learning"},
                    new ArXivCategory {Code = "cs.LO", Description = "Logic in Computer Science"},
                    new ArXivCategory {Code = "cs.MA", Description = "Multiagent Systems"},
                    new ArXivCategory {Code = "cs.MM", Description = "Multimedia"},
                    new ArXivCategory {Code = "cs.MS", Description = "Mathematical Software"},
                    new ArXivCategory {Code = "cs.NA", Description = "Numerical Analysis"},
                    new ArXivCategory {Code = "cs.NE", Description = "Neural and Evolutionary Computing"},
                    new ArXivCategory {Code = "cs.NI", Description = "Networking and Internet Architecture"},
                    new ArXivCategory {Code = "cs.OH", Description = "Other Computer Science"},
                    new ArXivCategory {Code = "cs.OS", Description = "Operating Systems"},
                    new ArXivCategory {Code = "cs.PF", Description = "Performance"},
                    new ArXivCategory {Code = "cs.PL", Description = "Programming Languages"},
                    new ArXivCategory {Code = "cs.RO", Description = "Robotics"},
                    new ArXivCategory {Code = "cs.SC", Description = "Symbolic Computation"},
                    new ArXivCategory {Code = "cs.SD", Description = "Sound"},
                    new ArXivCategory {Code = "cs.SE", Description = "Software Engineering"},
                    new ArXivCategory {Code = "cs.SI", Description = "Social and Information Networks"},
                    new ArXivCategory {Code = "cs.SY", Description = "Systems and Control"},
                    new ArXivCategory {Code = "econ.EM", Description = "Econometrics"},
                    new ArXivCategory {Code = "econ.GN", Description = "General Economics"},
                    new ArXivCategory {Code = "econ.TH", Description = "Theoretical Economics"},
                    new ArXivCategory {Code = "eess.AS", Description = "Audio and Speech Processing"},
                    new ArXivCategory {Code = "eess.IV", Description = "Image and Video Processing"},
                    new ArXivCategory {Code = "eess.SP", Description = "Signal Processing"},
                    new ArXivCategory {Code = "eess.SY", Description = "Systems and Control"},
                    new ArXivCategory {Code = "math.AC", Description = "Commutative Algebra"},
                    new ArXivCategory {Code = "math.AG", Description = "Algebraic Geometry"},
                    new ArXivCategory {Code = "math.AP", Description = "Analysis of PDEs"},
                    new ArXivCategory {Code = "math.AT", Description = "Algebraic Topology"},
                    new ArXivCategory {Code = "math.CA", Description = "Classical Analysis and ODEs"},
                    new ArXivCategory {Code = "math.CO", Description = "Combinatorics"},
                    new ArXivCategory {Code = "math.CT", Description = "Category Theory"},
                    new ArXivCategory {Code = "math.CV", Description = "Complex Variables"},
                    new ArXivCategory {Code = "math.DG", Description = "Differential Geometry"},
                    new ArXivCategory {Code = "math.DS", Description = "Dynamical Systems"},
                    new ArXivCategory {Code = "math.FA", Description = "Functional Analysis"},
                    new ArXivCategory {Code = "math.GM", Description = "General Mathematics"},
                    new ArXivCategory {Code = "math.GN", Description = "General Topology"},
                    new ArXivCategory {Code = "math.GR", Description = "Group Theory"},
                    new ArXivCategory {Code = "math.GT", Description = "Geometric Topology"},
                    new ArXivCategory {Code = "math.HO", Description = "History and Overview"},
                    new ArXivCategory {Code = "math.IT", Description = "Information Theory"},
                    new ArXivCategory {Code = "math.KT", Description = "K-Theory and Homology"},
                    new ArXivCategory {Code = "math.LO", Description = "Logic"},
                    new ArXivCategory {Code = "math.MG", Description = "Metric Geometry"},
                    new ArXivCategory {Code = "math.MP", Description = "Mathematical Physics"},
                    new ArXivCategory {Code = "math.NA", Description = "Numerical Analysis"},
                    new ArXivCategory {Code = "math.NT", Description = "Number Theory"},
                    new ArXivCategory {Code = "math.OA", Description = "Operator Algebras"},
                    new ArXivCategory {Code = "math.OC", Description = "Optimization and Control"},
                    new ArXivCategory {Code = "math.PR", Description = "Probability"},
                    new ArXivCategory {Code = "math.QA", Description = "Quantum Algebra"},
                    new ArXivCategory {Code = "math.RA", Description = "Rings and Algebras"},
                    new ArXivCategory {Code = "math.RT", Description = "Representation Theory"},
                    new ArXivCategory {Code = "math.SG", Description = "Symplectic Geometry"},
                    new ArXivCategory {Code = "math.SP", Description = "Spectral Theory"},
                    new ArXivCategory {Code = "math.ST", Description = "Statistics Theory"},
                    new ArXivCategory {Code = "astro-ph.CO", Description = "Cosmology and Nongalactic Astrophysics"},
                    new ArXivCategory {Code = "astro-ph.EP", Description = "Earth and Planetary Astrophysics"},
                    new ArXivCategory {Code = "astro-ph.GA", Description = "Astrophysics of Galaxies"},
                    new ArXivCategory {Code = "astro-ph.HE", Description = "High Energy Astrophysical Phenomena"},
                    new ArXivCategory {Code = "astro-ph.IM", Description = "Instrumentation and Methods for Astrophysics"},
                    new ArXivCategory {Code = "astro-ph.SR", Description = "Solar and Stellar Astrophysics"},
                    new ArXivCategory {Code = "cond-mat.dis-nn", Description = "Disordered Systems and Neural Networks"},
                    new ArXivCategory {Code = "cond-mat.mes-hall", Description = "Mesoscale and Nanoscale Physics"},
                    new ArXivCategory {Code = "cond-mat.mtrl-sci", Description = "Materials Science"},
                    new ArXivCategory {Code = "cond-mat.other", Description = "Other Condensed Matter"},
                    new ArXivCategory {Code = "cond-mat.quant-gas", Description = "Quantum Gases"},
                    new ArXivCategory {Code = "cond-mat.soft", Description = "Soft Condensed Matter"},
                    new ArXivCategory {Code = "cond-mat.stat-mech", Description = "Statistical Mechanics"},
                    new ArXivCategory {Code = "cond-mat.str-el", Description = "Strongly Correlated Electrons"},
                    new ArXivCategory {Code = "cond-mat.supr-con", Description = "Superconductivity"},
                    new ArXivCategory {Code = "gr-qc", Description = "General Relativity and Quantum Cosmology"},
                    new ArXivCategory {Code = "hep-ex", Description = "High Energy Physics - Experiment"},
                    new ArXivCategory {Code = "hep-lat", Description = "High Energy Physics - Lattice"},
                    new ArXivCategory {Code = "hep-ph", Description = "High Energy Physics - Phenomenology"},
                    new ArXivCategory {Code = "hep-th", Description = "High Energy Physics - Theory"},
                    new ArXivCategory {Code = "math-ph", Description = "Mathematical Physics"},
                    new ArXivCategory {Code = "nlin.AO", Description = "Adaptation and Self-Organizing Systems"},
                    new ArXivCategory {Code = "nlin.CD", Description = "Chaotic Dynamics"},
                    new ArXivCategory {Code = "nlin.CG", Description = "Cellular Automata and Lattice Gases"},
                    new ArXivCategory {Code = "nlin.PS", Description = "Pattern Formation and Solitons"},
                    new ArXivCategory {Code = "nlin.SI", Description = "Exactly Solvable and Integrable Systems"},
                    new ArXivCategory {Code = "nucl-ex", Description = "Nuclear Experiment"},
                    new ArXivCategory {Code = "nucl-th", Description = "Nuclear Theory"},
                    new ArXivCategory {Code = "physics.acc-ph", Description = "Accelerator Physics"},
                    new ArXivCategory {Code = "physics.ao-ph", Description = "Atmospheric and Oceanic Physics"},
                    new ArXivCategory {Code = "physics.app-ph", Description = "Applied Physics"},
                    new ArXivCategory {Code = "physics.atm-clus", Description = "Atomic and Molecular Clusters"},
                    new ArXivCategory {Code = "physics.atom-ph", Description = "Atomic Physics"},
                    new ArXivCategory {Code = "physics.bio-ph", Description = "Biological Physics"},
                    new ArXivCategory {Code = "physics.chem-ph", Description = "Chemical Physics"},
                    new ArXivCategory {Code = "physics.class-ph", Description = "Classical Physics"},
                    new ArXivCategory {Code = "physics.comp-ph", Description = "Computational Physics"},
                    new ArXivCategory {Code = "physics.data-an", Description = "Data Analysis, Statistics and Probability"},
                    new ArXivCategory {Code = "physics.ed-ph", Description = "Physics Education"},
                    new ArXivCategory {Code = "physics.flu-dyn", Description = "Fluid Dynamics"},
                    new ArXivCategory {Code = "physics.gen-ph", Description = "General Physics"},
                    new ArXivCategory {Code = "physics.geo-ph", Description = "Geophysics"},
                    new ArXivCategory {Code = "physics.hist-ph", Description = "History and Philosophy of Physics"},
                    new ArXivCategory {Code = "physics.ins-det", Description = "Instrumentation and Detectors"},
                    new ArXivCategory {Code = "physics.med-ph", Description = "Medical Physics"},
                    new ArXivCategory {Code = "physics.optics", Description = "Optics"},
                    new ArXivCategory {Code = "physics.plasm-ph", Description = "Plasma Physics"},
                    new ArXivCategory {Code = "physics.pop-ph", Description = "Popular Physics"},
                    new ArXivCategory {Code = "physics.soc-ph", Description = "Physics and Society"},
                    new ArXivCategory {Code = "physics.space-ph", Description = "Space Physics"},
                    new ArXivCategory {Code = "quant-ph", Description = "Quantum Physics"},
                    new ArXivCategory {Code = "q-bio.BM", Description = "Biomolecules"},
                    new ArXivCategory {Code = "q-bio.CB", Description = "Cell Behavior"},
                    new ArXivCategory {Code = "q-bio.GN", Description = "Genomics"},
                    new ArXivCategory {Code = "q-bio.MN", Description = "Molecular Networks"},
                    new ArXivCategory {Code = "q-bio.NC", Description = "Neurons and Cognition"},
                    new ArXivCategory {Code = "q-bio.OT", Description = "Other Quantitative Biology"},
                    new ArXivCategory {Code = "q-bio.PE", Description = "Populations and Evolution"},
                    new ArXivCategory {Code = "q-bio.QM", Description = "Quantitative Methods"},
                    new ArXivCategory {Code = "q-bio.SC", Description = "Subcellular Processes"},
                    new ArXivCategory {Code = "q-bio.TO", Description = "Tissues and Organs"},
                    new ArXivCategory {Code = "q-fin.CP", Description = "Computational Finance"},
                    new ArXivCategory {Code = "q-fin.EC", Description = "Economics"},
                    new ArXivCategory {Code = "q-fin.GN", Description = "General Finance"},
                    new ArXivCategory {Code = "q-fin.MF", Description = "Mathematical Finance"},
                    new ArXivCategory {Code = "q-fin.PM", Description = "Portfolio Management"},
                    new ArXivCategory {Code = "q-fin.PR", Description = "Pricing of Securities"},
                    new ArXivCategory {Code = "q-fin.RM", Description = "Risk Management"},
                    new ArXivCategory {Code = "q-fin.ST", Description = "Statistical Finance"},
                    new ArXivCategory {Code = "q-fin.TR", Description = "Trading and Market Microstructure"},
                    new ArXivCategory {Code = "stat.AP", Description = "Applications"},
                    new ArXivCategory {Code = "stat.CO", Description = "Computation"},
                    new ArXivCategory {Code = "stat.ME", Description = "Methodology"},
                    new ArXivCategory {Code = "stat.ML", Description = "Machine Learning"},
                    new ArXivCategory {Code = "stat.OT", Description = "Other Statistics"},
                    new ArXivCategory {Code = "stat.TH", Description = "Statistics Theory"}
                };
            }
        }
    }
}